[build]
	publish = "dist"
	command = "npm run build"

[[plugins]]

	# Opt-in to the Netlify Lighthouse plugin (choose one):

	# 1. Go to your site on https://app.netlify.com and navigate to the Integrations tab, search for the `Lighthouse` plugin
	# 2. Or via `npm install -D @netlify/plugin-lighthouse`

	# Read more: https://github.com/netlify/netlify-plugin-lighthouse

	package = "@netlify/plugin-lighthouse"

	# optional, fails build when a category is below a threshold
	# performance and accessibility will be rock solid with this but
	# there's no way we can get best-practices and seo as this site 
	# is both html and a script that can be directly run
	[plugins.inputs.thresholds]
		performance = 1.0
		accessibility = 1.0
		best-practices = 0.75
		seo = 0.75

	[plugins.inputs]
		output_path = "reports/lighthouse/index.html"
		
		[plugins.inputs.settings]
    		preset = "desktop"